spring:
  application:
    name: easypoi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?serverTimezone=UTC
    password: 123456
    username: root
server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*xml